# Generated by Django 3.0.7 on 2020-08-06 03:42

from django.db import migrations, models
import wrinkledetect.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_fn', models.FileField(null=True, upload_to='upload_img', validators=[wrinkledetect.validators.validate_file_extension], verbose_name='Upload Resume')),
                ('img_analysis_json', models.TextField(null=True, verbose_name='Analysis JSON')),
            ],
        ),
    ]
