# Generated by Django 3.0.7 on 2020-08-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrinkledetect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='seat_serial',
            field=models.CharField(max_length=50, null=True, verbose_name='Seat Serial Id'),
        ),
    ]
