# Generated by Django 3.0.7 on 2020-08-07 01:34

from django.db import migrations, models
import wrinkledetect.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wrinkledetect', '0002_imageanalysis_seat_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanalysis',
            name='img_fn',
            field=models.ImageField(null=True, upload_to='upload_img', validators=[wrinkledetect.validators.validate_file_extension], verbose_name='Select Image'),
        ),
    ]
