# Generated by Django 3.0.7 on 2020-08-07 13:35

from django.db import migrations, models
import wrinkledetect.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wrinkledetect', '0003_auto_20200807_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='img_anly_fn',
            field=models.ImageField(null=True, upload_to='upload_img', validators=[wrinkledetect.validators.validate_file_extension], verbose_name='Select Image'),
        ),
    ]
