# Generated by Django 3.0.7 on 2020-08-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrinkledetect', '0006_imageanalysis_num_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanalysis',
            name='img_anly_end_time',
            field=models.TimeField(auto_now=True, verbose_name='End Time: '),
        ),
        migrations.AlterField(
            model_name='imageanalysis',
            name='img_anly_start_time',
            field=models.TimeField(auto_now=True, verbose_name='Start Time: '),
        ),
    ]
